---
 - name: Enable httpd Service in Firewalld
   firewalld:
          zone: public
          port: 80/tcp
          permanent: yes
          state: enabled

 - name: Reload the firewall rules
   shell: firewall-cmd --reload
